### ISSUE TITLE
incorrect API call for retreiving questions for answering

### ISSUE THREAD

**Issue by tambre** [tambre/ibmqa#14]
Currently this API is called
GET /domain/{domainId}/questionnaires

instead the below one should be called
GET /domain/{domainId}/questionnaire/active

**Comment by tambre** [comment]
http://ibm360-pc0c9ax7.in.ibm.com:11102/ibmqa/domain/{domainId}/questionnaires/active

**Comment by rashmipadale** [comment]
Fixed.
